awsenv-current renamed to awsenv-default

diff --git a/bin/awsenv-init b/bin/awsenv-init
--- a/bin/awsenv-init
+++ b/bin/awsenv-init
@@ -13,23 +13,23 @@ if [ $# -eq 0 ]; then
 fi
 
 if [ "$1" == "-" ]; then 
-    CURRENT="$(awsenv current)"
+    DEFAULT="$(awsenv default)"
 
-    if [ "$CURRENT" == "" ]; then
+    if [ "$DEFAULT" == "" ]; then
         echo "# $(awsenv version)"
         echo "# error: you have to set a environment with 'awsenv use' first."
         exit 1
     fi
 else
-    CURRENT="$1"
+    DEFAULT="$1"
 fi
 
 AWSENV_ROOT="$(awsenv root)"
-ENVIRONMENT="$AWSENV_ROOT/envs/$CURRENT"
+ENVIRONMENT="$AWSENV_ROOT/envs/$DEFAULT"
 
 if [ ! -d "$ENVIRONMENT" ]; then
     awsenv version
-    echo "error: there is no environment named '$CURRENT'." >&2
+    echo "error: there is no environment named '$DEFAULT'." >&2
     exit 1
 fi
 
@@ -38,7 +38,7 @@ function exportAwsEnvGlobals()
     echo ""
     echo "# Let others detect us" 
     echo "export AWSENV_LOADED=1"
-    echo "export AWSENV_NAME='$CURRENT'"
+    echo "export AWSENV_NAME='$DEFAULT'"
 }
 
 function exportNewPath()
diff --git a/bin/awsenv-use b/bin/awsenv-use
--- a/bin/awsenv-use
+++ b/bin/awsenv-use
@@ -11,23 +11,23 @@ if [ $# -eq 0 ]; then
     exit 1
 fi
 
-NEW_CURRENT="$1"
-OLD_CURRENT="$(awsenv current)"
+NEW_DEFAULT="$1"
+OLD_DEFAULT="$(awsenv default)"
 
-if [ "$OLD_CURRENT" == "$NEW_CURRENT" ]; then
+if [ "$OLD_DEFAULT" == "$NEW_DEFAULT" ]; then
     exit 0
 fi
 
 AWSENV_ROOT="$(awsenv root)"
-ENVIRONMENT="$AWSENV_ROOT/envs/$NEW_CURRENT"
+ENVIRONMENT="$AWSENV_ROOT/envs/$NEW_DEFAULT"
 
 if [ ! -d "$ENVIRONMENT" ]; then
     awsenv version
-    echo "error: there is no environment named '$NEW_CURRENT'." >&2
+    echo "error: there is no environment named '$NEW_DEFAULT'." >&2
     exit 1
 fi
 
-echo "$NEW_CURRENT" > "$AWSENV_ROOT/current"
+echo "$NEW_DEFAULT" > "$AWSENV_ROOT/default"
 
 awsenv version
 echo "notice: the environment has to be activated with: eval \"\$(awsenv init -)\""
